services:
  erp-cini:
    image: erp-cini:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp-cini
    restart: unless-stopped
    ports:
      - "3003:3003"
    env_file:
      - .env
    environment:
      CERT_DIR: C:/certs
    volumes:
      - ./uploads:C:/app/uploads
      - C:/Projetos/Certificados:C:/certs:ro
